from setuptools import setup, find_packages

setup(
    name="repomirror",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "PyGithub>=2.1.1",
        "boto3>=1.26.0",
        "google-api-python-client>=2.86.0",
        "google-auth-httplib2>=0.1.0",
        "google-auth-oauthlib>=1.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.22.0",
        "python-multipart>=0.0.6",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "sqlalchemy>=2.0.0",
        "alembic>=1.11.0",
        "pydantic>=2.0.0",
        "python-dotenv>=1.0.0",
        "click>=8.1.3",
        "rich>=13.3.5",
        "cryptography>=41.0.0",
        "pyyaml>=6.0.1",
        "tqdm>=4.65.0",
        "aiofiles>=23.1.0",
        "python-magic>=0.4.27",
    ],
    entry_points={
        "console_scripts": [
            "repomirror=repomirror.cli:main",
        ],
    },
    author="Tu Nombre",
    author_email="tu@email.com",
    description="Herramienta para clonar y respaldar repositorios de GitHub",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/tuusuario/repomirror",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
) 